import type { JobEmail } from '../types'

const now = Date.now()
const hours = (h: number) => new Date(now - h * 3600000).toISOString()
const days = (d: number) => new Date(now - d * 86400000).toISOString()

export const SEED_EMAILS: JobEmail[] = [
  // Offers
  {
    id: 'seed-offer-1',
    threadId: 'thread-offer-1',
    sender: 'Talent Team <noreply@greenhouse.io>',
    subject: 'Offer Letter — Frontend Engineer at Stripe',
    snippet: 'Congratulations! We are pleased to offer you the position of Frontend Engineer. Please review the attached offer letter...',
    date: hours(2),
    category: 'offer',
    seen: false,
    dismissed: false,
  },

  // Interview Requests
  {
    id: 'seed-interview-1',
    threadId: 'thread-interview-1',
    sender: 'Recruiting <notifications@lever.co>',
    subject: 'Interview: Senior React Developer — Vercel',
    snippet: "We'd like to schedule a call to discuss the Senior React Developer role. Are you available this Thursday at 2pm PST?",
    date: hours(5),
    category: 'interview_request',
    seen: false,
    dismissed: false,
  },
  {
    id: 'seed-interview-2',
    threadId: 'thread-interview-2',
    sender: 'Ashby <no-reply@ashbyhq.com>',
    subject: 'Next steps — Full Stack Engineer at Linear',
    snippet: 'Hi! The team enjoyed your initial conversation. We would love to have you meet the engineering team for a virtual onsite...',
    date: hours(18),
    category: 'interview_request',
    seen: false,
    dismissed: false,
  },
  {
    id: 'seed-interview-3',
    threadId: 'thread-interview-3',
    sender: 'Talent Acquisition <recruiting@smartrecruiters.com>',
    subject: 'Phone screen — Product Engineer at Notion',
    snippet: 'Thank you for applying. We would like to schedule a phone screen with our engineering manager. Please use the link below...',
    date: days(2),
    category: 'interview_request',
    seen: true,
    dismissed: false,
  },

  // Rejections
  {
    id: 'seed-rejection-1',
    threadId: 'thread-rejection-1',
    sender: 'Careers <noreply@myworkday.com>',
    subject: 'Update on your application — Datadog',
    snippet: 'Unfortunately, after careful consideration, we have decided not to proceed with your application at this time...',
    date: hours(8),
    category: 'rejection',
    seen: false,
    dismissed: false,
  },
  {
    id: 'seed-rejection-2',
    threadId: 'thread-rejection-2',
    sender: 'Greenhouse <no-reply@greenhouse.io>',
    subject: 'Your application to Figma',
    snippet: 'We appreciate your interest in Figma. After reviewing your profile, we have decided to move forward with other candidates...',
    date: days(1),
    category: 'rejection',
    seen: false,
    dismissed: false,
  },
  {
    id: 'seed-rejection-3',
    threadId: 'thread-rejection-3',
    sender: 'Recruiting <jobs@lever.co>',
    subject: 'Application update — Shopify',
    snippet: 'Thank you for taking the time to interview with us. Unfortunately, we will not be moving forward at this time...',
    date: days(3),
    category: 'rejection',
    seen: true,
    dismissed: false,
  },

  // Application Confirmations
  {
    id: 'seed-confirm-1',
    threadId: 'thread-confirm-1',
    sender: 'LinkedIn <jobs-noreply@linkedin.com>',
    subject: 'Application submitted: Staff Engineer at Netflix',
    snippet: "Thank you for applying to Staff Engineer at Netflix. We've received your application and will review it shortly...",
    date: hours(1),
    category: 'application_confirmation',
    seen: false,
    dismissed: false,
  },
  {
    id: 'seed-confirm-2',
    threadId: 'thread-confirm-2',
    sender: 'Greenhouse <noreply@greenhouse.io>',
    subject: 'We received your application — Airbnb',
    snippet: 'Thank you for your interest in the Software Engineer position at Airbnb. Your application has been received...',
    date: hours(12),
    category: 'application_confirmation',
    seen: false,
    dismissed: false,
  },
  {
    id: 'seed-confirm-3',
    threadId: 'thread-confirm-3',
    sender: 'SmartRecruiters <no-reply@smartrecruiters.com>',
    subject: 'Application received — Coinbase',
    snippet: 'We have successfully received your application for the Frontend Engineer role at Coinbase. Our team will review...',
    date: days(2),
    category: 'application_confirmation',
    seen: true,
    dismissed: false,
  },
  {
    id: 'seed-confirm-4',
    threadId: 'thread-confirm-4',
    sender: 'iCIMS <notifications@icims.com>',
    subject: 'Thank you for applying — Dropbox',
    snippet: 'Thank you for applying to the Senior Engineer position at Dropbox. We will review your application and get back...',
    date: days(4),
    category: 'application_confirmation',
    seen: true,
    dismissed: false,
  },

  // Other
  {
    id: 'seed-other-1',
    threadId: 'thread-other-1',
    sender: 'LinkedIn <messages-noreply@linkedin.com>',
    subject: 'New message from a recruiter at Google',
    snippet: "Hi, I came across your profile and I think you'd be a great fit for a role we have open on the Search team...",
    date: hours(6),
    category: 'other',
    seen: false,
    dismissed: false,
  },

  // History emails (older than 7 days)
  {
    id: 'seed-history-1',
    threadId: 'thread-history-1',
    sender: 'Lever <no-reply@lever.co>',
    subject: 'Application update — Slack',
    snippet: 'Thank you for your interest in Slack. Unfortunately, we have decided to pursue other candidates for this role...',
    date: days(10),
    category: 'rejection',
    seen: true,
    dismissed: false,
  },
  {
    id: 'seed-history-2',
    threadId: 'thread-history-2',
    sender: 'Greenhouse <noreply@greenhouse.io>',
    subject: 'We received your application — Spotify',
    snippet: 'Thank you for applying to Spotify. Your application has been received and is currently under review...',
    date: days(14),
    category: 'application_confirmation',
    seen: true,
    dismissed: false,
  },
  {
    id: 'seed-history-3',
    threadId: 'thread-history-3',
    sender: 'Workday <noreply@myworkday.com>',
    subject: 'Interview invitation — Meta',
    snippet: 'We would like to invite you for a technical phone screen for the Software Engineer position at Meta...',
    date: days(12),
    category: 'interview_request',
    seen: true,
    dismissed: false,
  },
]
